---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'current' %>
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || "auto" %>

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: repository
    run_list:
      - recipe[test::repository]
  - name: client_install
    run_list:
      - recipe[test::client_install]
  - name: server_install
    run_list:
      - recipe[test::server_install]
  - name: server_configuration
    run_list:
      - recipe[test::server_configuration]
  - name: resources
    run_list:
      - recipe[test::user_database]
  - name: replication
    run_list:
      - recipe[test::replication]
  - name: datadir_changed
    run_list:
      - recipe[test::datadir_changed]
